### PR TITLE
add an example in Vue.js

### PR DESCRIPTION
**Pull request by medmin**
Hi, there, 

I have built an example in Vue.js and it looks nice. May I submit a pull request ? Thanks.

https://github.com/whizjs/netlify-identity-demo-vue

### CODE REVIEW

**Comment by futuregerald** [comment]
LGTM @bcomnes

**Comment by medmin** [comment]
Hi @bcomnes Bret, I have set up a little repo :  https://github.com/whizjs/netlify-identity-demo-vue

And the current demo is deployed on netlify. The url is :  https://netlify-identity-demo-vue.netlify.com/

I will maintain the repo and the demo and keep it updated, like upgrading it to Vue 3.0 in 2019 (Vue 3.0 will be released in 2019.) 

I am not sure what I need to do. 

> Can you add a vue folder in the examples folder with a README.md linking to this example in a repo you maintain instead?

There is just an example folder in the repo and it's a React demo in it. And there is already a README file. I mean, if you don't merge my PR, that's OK and you can just add my repo link to the README file.


Anyway, thank you for reviewing my PR and I will keep maintaining it.

**Comment by bcomnes** [comment]
Oh yeah, good point.  We should move the contents of `/example` into `/example/react` and then create a folder in `/example` called `vue` (e.g. `/example/vue`) and put the README with a link to your repo in there.  Sound good?  I can do this if you prefer lmk.

**Comment by medmin** [comment]
@bcomnes Yes, that would work. Thanks.

**Pull request merged**
