### PR TITLE
chore: update Netlify logo

### PR DESCRIPTION
**Pull request by Hrishikesh-K**
Updated the Netlify logo in the widget to match the current logo. Looks like:

image

### CODE REVIEW

**Comment by iKristy** [comment]
Hey @Hrishikesh-K, I apologize for for the unsolicited lurk 👀 (I saw your ping in the Final Boss channel) I appreciate you providing the fix and think this looks great!

I might have an absolutely tiny, non-blocking nit: because of the logo being placed on the modal overlay, and the accompanying de-emphasized text, the colored version of the logo feels slightly clashing with the overlay background color. So, I was wondering if using the monochrome variant of the encapsulated logo  ([from our press page](https://www.netlify.com/press/#logos)) might fit visually a little bit more overall.

CleanShot 2023-05-22 at 14 52 59@2x<br>



I wanted to try to see how it would look like, so I hacked it in Devtools. In case it's useful, here's the base64 encoding of the logo:
```
PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xOC4zMDY1IDAuNzAyNjg2TDMxLjI5NzMgMTMuNjkzNUwzMS43Nzg3IDE0LjE3NkwzMiAxNC43MDk3VjE3LjI5MDNMMzEuNzc4NyAxNy44MjRMMzEuMjk3MyAxOC4zMDY1TDE4LjMwNjUgMzEuMjk3M0wxNy44MjQgMzEuNzc4N0wxNy4yOTAzIDMySDE0LjcwOTdMMTQuMTc2IDMxLjc3ODdMMTMuNjkzNSAzMS4yOTczTDAuNzAyNjg2IDE4LjMwNjVMMC4yMjEyNTcgMTcuODI0TDAgMTcuMjkwM1YxNC43MDk3TDAuMjIxMjU3IDE0LjE3NkwwLjcwMjY4NiAxMy42OTM1TDEzLjY5MzUgMC43MDI2ODZMMTQuMTc2IDAuMjIxMjU3TDE0LjcwOTcgMEgxNy4yOTAzTDE3LjgyNCAwLjIyMTI1N0wxOC4zMDY1IDAuNzAyNjg2Wk0xNC44NDIgMjIuNzYzOVYyOS4wMDQ3TDE1LjAwNzcgMjkuMTcwNEgxNi45OTM0TDE3LjE1OTEgMjkuMDA0N1YyMi43NjM5TDE2Ljk5MzQgMjIuNTk4MkgxNS4wMDc3TDE0Ljg0MiAyMi43NjM5Wk0xNC44NDIgOS4yMzYxVjIuOTk1MzJMMTUuMDA3NyAyLjgyOTY1SDE2Ljk5MzRMMTcuMTU5MSAyLjk5NTMyVjkuMjM2MUwxNi45OTM0IDkuNDAxNzZIMTUuMDA3N0wxNC44NDIgOS4yMzYxWk05LjMyMzk0IDI0LjM4MDVIOS41OTc0NUwxMS40MTUzIDIyLjU2MTZWMjEuMTE3M0wxMS4yMjE5IDIwLjkyNDlMOS43Nzc1NyAyMC45MjM4TDcuOTU5NyAyMi43NDI4VjIzLjAxNjNMOS4zMjM5NCAyNC4zODA1Wk03Ljk1OTcgOS4zMjYxNlY5LjA1Mzc2TDkuMzIzOTQgNy42ODg0MUg5LjU5NjM0TDExLjQxNTMgOS41MDczOVYxMC45NTA2TDExLjIyMyAxMS4xNDUxSDkuNzc4NjhMNy45NTk3IDkuMzI2MTZaTTkuNDg0MDQgMTQuODM4N0gyLjQ2NDk3TDIuMjk5MyAxNS4wMDQzVjE2Ljk5MjNMMi40NjQ5NyAxNy4xNThIOS40ODQwNEw5LjY0OTcxIDE2Ljk5MjNWMTUuMDA0M0w5LjQ4NDA0IDE0LjgzODdaTTE5LjcxODYgMjAuMTM0NEgxNy43MzYyTDE3LjU3MDUgMTkuOTY4N1YxNS4zMjM1QzE3LjU3MTYgMTQuNDk2MiAxNy4yNDY5IDEzLjg1NTggMTYuMjQ4NSAxMy44MzQ3QzE1LjczNTkgMTMuODIxMyAxNS4xNDc4IDEzLjgzNDcgMTQuNTIwNyAxMy44NjAzTDE0LjQyNjIgMTMuOTU3TDE0LjQyNzMgMTkuOTY4N0wxNC4yNjE2IDIwLjEzNDRIMTIuMjc3TDEyLjExMTMgMTkuOTY4N1YxMi4wMzEzTDEyLjI3NyAxMS44NjU2SDE2Ljc0MjJDMTguNDc3OCAxMS44NjU2IDE5Ljg4NDIgMTMuMjcyMSAxOS44ODQyIDE1LjAwNzdWMTkuOTY4N0wxOS43MTg2IDIwLjEzNDRaTTIyLjUxNiAxNy4xNjEzSDI5LjUzNUwyOS43MDA3IDE2Ljk5NTdWMTUuMDA3N0wyOS41MzUgMTQuODQySDIyLjUxNkwyMi4zNTAzIDE1LjAwNzdWMTYuOTk1N0wyMi41MTYgMTcuMTYxM1oiIGZpbGw9IiM5REE3QjIiLz4KPC9zdmc+Cg==
```

**Comment by Hrishikesh-K** [comment]
Done! This has been updated.

**Review by iKristy — APPROVED** [review]
Reviewed the DP and looks great!! Thank you for including the feedback, too, Hrishikesh.

**Review by mraerino — COMMENTED** [review]
sgtm. i don't see why this would break anything

**Review by mraerino — COMMENTED** [review]
sgtm. i don't see why this would break anything

**Review by mraerino — APPROVED** [review]

**Pull request merged**
