### PR TITLE
feat: Mandarin Translation

### PR DESCRIPTION
**Pull request by ymcheung**
Mandarin translation for Taiwan and Hong Kong
台灣與香港使用的中文翻譯

### CODE REVIEW

**Review by cassidoo — CHANGES_REQUESTED** [review]
Instead of zhTW, could you use zhTraditional? 

For email, no need to use the English words, you can use 郵箱 or 電子郵箱 for those ones so we can translate it all.

For the "continue with" section, mind switching to 登入使用?

**Comment by ymcheung** [comment]
> Instead of zhTW, could you use zhTraditional?

Sure!

> For email, no need to use the English words, you can use 郵箱 or 電子郵箱 for those ones so we can translate it all.

In zhTraditional, this would be "電子郵件".

> For the "continue with" section, mind switching to 登入使用?

In zhTraditional, it's great to use "使用 [provider] 登入". For example, "使用 Google 登入".
However, interpolation might break other languages, I think? So I chose "透過", which would be more accurate than using "使用" only.

**Comment by marierigal** [comment]
@ymcheung You can check #373 for a little update on translations 😉

**Comment by ymcheung** [comment]
> @ymcheung You can check #373 for a little update on translations 😉

Updated! :)

**Pull request closed without merging**
